brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
format_strings = true
indent_style = "Block"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Crate"
newline_style = "Unix"
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
